[package]
name = "gb-checker"
version = "0.1.0"
authors = ["Florian Sextl <sextl@in.tum.de>"]

[dependencies]
chrono = "0.4"
rustc-serialize = "0.3"
regex = "1"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0"
[dependencies.winapi]
version = "0.3" 
features = ["winuser"]
