[package]
name = "new_rust_project"
version = "0.1.0"
authors = ["Flo <sextl@in.tum.de>"]

[dependencies]
chrono = "0.4"
rustc-serialize = "0.3"
[dependencies.winapi]
version = "0.3" 
features = ["winuser"]
